- name: "Test directory {{ directory }}"
  ansible.builtin.stat:
    path: "{{ librenms_install_root }}/{{ directory }}"
  register: dirstat
  changed_when: not dirstat.stat.exists

- name: "Create directory {{ directory }}"
  become_method: ansible.builtin.sudo
  become: true
  notify: Run restore context to reload selinux
  when: not dirstat.stat.exists
  ansible.builtin.file:
    path: "{{ librenms_install_root }}/{{ directory }}"
    state: directory
    mode: "0775"
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}"
    # seuser: system_u
    # serole: object_r
    # setype: container_file_t
    # selevel: s0
- name: "Stat directory {{ directory }}"
  become_method: containers.podman.podman_unshare
  become: true
  ansible.builtin.stat:
    path: "{{ librenms_install_root }}/{{ directory }}"
  register: podmandirstat

- name: Display Stat for {{ directory }}
  ansible.builtin.debug:
    var: podmandirstat.stat
  when: false

- name: Give access to container user on {{ directory }}
  become_method: containers.podman.podman_unshare
  # become_user: 1000
  become: true
  ansible.builtin.file:
    path: "{{ librenms_install_root }}/{{ directory }}"
    state: directory
    owner: "1000"
    group: "1000"
    recurse: true
    mode: "0775"
  when:
    - podmandirstat.stat.uid != 1000
    - podmandirstat.stat.gid != 1000
    - podmandirstat.stat.mode != "0775"
