- name: Install Podman
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Gather Packages Facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Podman Install
      when:
        - ansible_facts.packages['podman'] is not defined
      ansible.builtin.include_role:
        name: podman
        apply:
          tags:
            - podman_fromcopr
            - podman_install
    - name: SELinux Tools
      block:
        - name: Install System Tools
          become: true
          when:
            - ansible_facts.packages['policycoreutils-python-utils'] is not defined
          ansible.builtin.package:
            name:
              - policycoreutils-python-utils
              # - python3-policycoreutils
            state: present

- name: Create the stage
  hosts: all
  gather_facts: true
  vars:
    librenms_install_root: "/opt/LibreNMS"
  tasks:
    - name: Include librenms
      ansible.builtin.include_role:
        name: librenms

- name: Play the kube
  hosts: all
  gather_facts: true
  vars:
    librenms_install_root: "/opt/LibreNMS"
  tasks:
    - name: Move the kube
      loop:
        - LibreNMS.kubeplay.yaml
        - LibreNMS.kube
      ansible.builtin.copy:
        dest: "{{ librenms_install_root }}/{{ item }}"
        src: "./{{ item }}"
        mode: "0644"
    - name: Install the .kube file in the user systemd
      block:
        - name: Link the file
          ansible.builtin.file:
            path: "$HOME/.config/containers/systemd"
            state: directory
            recurse: true
        - name: Link the file
          ansible.builtin.file:
            path: "$HOME/.config/containers/systemd/LibreNMS.kube"
            state: link
            src: "{{ librenms_install_root }}/LibreNMS.kube"
    - name: Reload SystemD
      ansible.builtin.systemd:
        scope: user
        daemon_reload: true
        name: LibreNMS
        state: restarted
